# This Kustomization file is ignored inside the Harness.io platform.

resources:
- persistent-volumes.yaml
- persistent-volume-claims.yaml
- ingress.yaml
- ingress-external.yaml
- ../../base

patchesStrategicMerge:
- deployment.yaml

