resources:
- persistent-volumes.yaml
- persistent-volume-claims.yaml
- ingress-external.yaml
- basic-auth-secret.yaml
- ../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: incora.azurecr.io/ics-service
  newTag: d22e942
