
resources:
- persistent-volumes.yaml
- persistent-volume-claims.yaml
- ../../base

patches:
- path: ingress.yaml
  target:
    kind: Ingress
    name: ics-service-ingress

patchesStrategicMerge:
- deployment.yaml
