apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: ics-service-dev
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "incora.azurecr.io": {
          "username": "980c0b8d-f53e-459f-b39c-8f2b43641cad",
          "password": "BCa8Q~he1SvAt9oislRBumEsHLs-pjbPgdU0Ebj-"
        }
      }
    }