apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: <github_URL>
  username: svc-incora-git
  password: <github_token>
  type: git

